"""Reproducibly import minizip-ng's reviewed Apple ZIP/AES source set.

Preparation happens in a sibling temporary directory. Only a fully prepared
result can replace vendor/, using an atomic rename (or swap on updates).
"""

import argparse
import ctypes
import fcntl
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tarfile
import tempfile

ROOT = Path(__file__).resolve().parents[2]
INTEGRATION = ROOT / "Scripts/minizip"
VENDOR = ROOT / "Sources/CMinizip/vendor"
UPSTREAM = "https://github.com/zlib-ng/minizip-ng"
SOURCES = (
    "mz_crypt.c", "mz_crypt_apple.c", "mz_os.c", "mz_os_posix.c",
    "mz_strm.c", "mz_strm_mem.c", "mz_strm_os_posix.c", "mz_strm_wzaes.c",
    "mz_strm_zlib.c", "mz_zip.c",
)
HEADERS = (
    "mz.h", "mz_crypt.h", "mz_os.h", "mz_strm.h", "mz_strm_mem.h",
    "mz_strm_os.h", "mz_strm_wzaes.h", "mz_strm_zlib.h", "mz_zip.h",
)


def run(*arguments):
    """Run an argument vector without shell expansion; fail on nonzero exit."""
    return subprocess.check_output(arguments, text=True).strip()


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def resolve_commit(ref):
    """Accept a full commit SHA or an exact tag; peel annotated tags."""
    if re.fullmatch(r"[0-9a-fA-F]{40}", ref):
        return ref.lower()
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._/-]*", ref) or ".." in ref:
        raise ValueError("Expected an exact tag or full 40-character commit")
    tag = "refs/tags/" + ref
    output = run("git", "ls-remote", "--exit-code", UPSTREAM + ".git", tag, tag + "^{}")
    refs = {}
    for line in output.splitlines():
        commit, name = line.split()
        refs[name] = commit
    commit = refs.get(tag + "^{}", refs.get(tag, ""))
    if not re.fullmatch(r"[0-9a-f]{40}", commit):
        raise ValueError("Could not resolve tag to an exact commit")
    return commit


def download_archive(commit, destination):
    url = "https://codeload.github.com/zlib-ng/minizip-ng/tar.gz/" + commit
    run("curl", "--fail", "--location", "--silent", "--show-error", "--retry", "3",
        "--connect-timeout", "30", "--max-time", "300", url, "-o", str(destination))
    return url


def validate_members(archive, prefix):
    """Validate the complete tar index; never extract arbitrary upstream paths."""
    seen = set()
    for member in archive.getmembers():
        if member.name in seen:
            raise ValueError("Duplicate archive member")
        seen.add(member.name)
        if not (member.name == prefix[:-1] or member.name.startswith(prefix)):
            raise ValueError("Unexpected archive root")
        if ".." in Path(member.name).parts or not (member.isfile() or member.isdir()):
            raise ValueError("Unsafe upstream archive structure")


def select_sources(archive_path, commit, destination):
    prefix = "minizip-ng-" + commit + "/"
    with tarfile.open(archive_path, "r:gz") as archive:
        validate_members(archive, prefix)
        for name in (*SOURCES, *HEADERS, "LICENSE"):
            member = archive.getmember(prefix + name)
            if not member.isfile() or member.size > 4 * 1024 * 1024:
                raise ValueError("Invalid selected source: " + name)
            with archive.extractfile(member) as source:
                (destination / name).write_bytes(source.read())


def write_configuration(destination):
    """Namespace all upstream C identifiers, including non-function globals."""
    source = "\n".join((destination / name).read_text() for name in (*SOURCES, *HEADERS))
    macros = set(re.findall(r"^\s*#\s*define\s+(mz_[A-Za-z0-9_]+)", source, re.MULTILINE))
    identifiers = sorted(set(re.findall(r"\bmz_[A-Za-z0-9_]+\b", source)) - macros)
    definitions = "".join(f"#define {name} magiczip_{name}\n" for name in identifiers)
    (destination / "magiczip_namespace.h").write_text(
        "/* Generated by Scripts/update-minizip.sh; do not edit. */\n"
        "#ifndef MAGICZIP_NAMESPACE_H\n#define MAGICZIP_NAMESPACE_H\n" + definitions + "#endif\n")
    shutil.copyfile(INTEGRATION / "config.h", destination / "mz_config.h")


def ordered_patches():
    """The reviewed series file, not filesystem ordering, controls patch order."""
    directory = INTEGRATION / "patches"
    names = [line.strip() for line in (directory / "series").read_text().splitlines()
             if line.strip() and not line.lstrip().startswith("#")]
    if len(names) != len(set(names)) or any(Path(name).name != name for name in names):
        raise ValueError("Invalid or duplicate patch in series")
    if set(names) != {path.name for path in directory.glob("*.patch")}:
        raise ValueError("series must list every patch exactly once")
    return [directory / name for name in names]


def apply_patches(destination):
    patches = ordered_patches()
    for patch in patches:
        run("patch", "--batch", "--fuzz=0", "-p1", "-d", str(destination), "-i", str(patch))
    return [{"file": patch.name, "sha256": sha256(patch)} for patch in patches]


def prepare(ref, work):
    commit = resolve_commit(ref)
    archive = work / "upstream.tar.gz"
    archive_url = download_archive(commit, archive)
    destination = work / "prepared"
    destination.mkdir()
    select_sources(archive, commit, destination)
    write_configuration(destination)
    patches = apply_patches(destination)
    metadata = {
        "upstream": UPSTREAM, "ref": ref, "commit": commit,
        "archive_url": archive_url, "archive_sha256": sha256(archive),
        "sources": sorted(SOURCES), "headers": sorted(HEADERS), "patches": patches,
        "configuration_sha256": sha256(destination / "mz_config.h"), "import_format": 1,
    }
    (destination / "METADATA.json").write_text(json.dumps(metadata, sort_keys=True, indent=2) + "\n")
    for path in destination.iterdir():
        path.chmod(0o644)
    destination.chmod(0o755)
    return destination, commit


def install(prepared):
    """Atomically install on macOS, preserving the old version on failure."""
    if VENDOR.is_symlink():
        raise ValueError("Refusing a symlink vendor directory")
    if not VENDOR.exists():
        prepared.rename(VENDOR)
        return
    libc = ctypes.CDLL(None, use_errno=True)
    rename_swap = 2  # RENAME_SWAP from Darwin's stdio.h.
    if libc.renamex_np(os.fsencode(prepared), os.fsencode(VENDOR), rename_swap) != 0:
        raise OSError(ctypes.get_errno(), "Atomic vendor swap failed")
    # The previous version now lives in the temporary directory and is cleaned up.


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ref", required=True, help="Exact upstream tag or full commit SHA")
    args = parser.parse_args()
    VENDOR.parent.mkdir(parents=True, exist_ok=True)
    with (VENDOR.parent / ".import.lock").open("w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        with tempfile.TemporaryDirectory(prefix=".import-", dir=VENDOR.parent) as temporary:
            prepared, commit = prepare(args.ref, Path(temporary))
            install(prepared)
    print("Imported minizip-ng " + args.ref + " at " + commit)


if __name__ == "__main__":
    main()
