/// The file or directory operation associated with a failure.
///
/// Switch over cases to handle specific operations. Raw strings are intended for diagnostics,
/// not localized user-facing messages.
public enum ZIPFileSystemOperation: String, Sendable, CaseIterable {
    case enumerateDirectory = "enumerate directory"
    case closeFailedEnumeration = "close failed enumeration"
    case closeEnumeration = "close enumeration"
    case inspectIdentity = "inspect identity"
    case openRoot = "open root"
    case closeDirectoryComponent = "close directory component"
    case openDirectory = "open directory"
    case closeSourceParent = "close source parent"
    case openFile = "open file"
    case closeRejectedSource = "close rejected source"
    case duplicateDirectory = "duplicate directory"
    case closeOutputParent = "close output parent"
    case createDirectory = "create directory"
    case openOutputDirectory = "open output directory"
    case writeOutput = "write output"
    case duplicateRoot = "duplicate root"
    case closeTraversalDirectory = "close traversal directory"
    case reopenDirectory = "reopen directory"
    case openEnumeration = "open enumeration"
    case readDirectory = "read directory"
    case closeCleanupParent = "close cleanup parent"
    case inspectCleanup = "inspect cleanup"
    case removeTemporaryOutput = "remove temporary output"
    case closeCleanup = "close cleanup"
    case removeDirectory = "remove directory"
    case createStagingDirectory = "create staging directory"
    case openStagingDirectory = "open staging directory"
    case removeFailedStaging = "remove failed staging"
    case createOutput = "create output"
    case inspectDestination = "inspect destination"
    case publishOutput = "publish output"
    case closeOutputDirectory = "close output directory"
    case closeOutput = "close output"
    case syncOutput = "sync output"
    case closeSource = "close source"
    case inspectSource = "inspect source"
    case closeSourceRoot = "close source root"
    case readSource = "read source"
    case closeSourceDirectory = "close source directory"
    case openSourceChild = "open source child"
    case closeSourceChild = "close source child"
}
